# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend generator CI test

on:
  push:
    branches: [ "main" ]
    paths:
      - 'App_Builder_frontend/**'
      # - 'App_Builder_Backend/**'
      # - 'User_App_AI/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'App_Builder_frontend/**'
      # - 'App_Builder_Backend/**'
      # - 'User_App_AI/**'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test Frontend generator
      run: |
        npm install
        npm run test:run
      working-directory: ./App_Builder_frontend
        
    # - name: Test Backend generator
    #   run: |
    #     npm install
    #     npm run test
    #   working-directory: ./App_Builder_Backend
        
    # - name: Test AI generator
    #   run: |
    #     npm install
    #     npm run test:run
    #   working-directory: ./User_App_AI
